# Change these first
owner: pinkstrings
repo: upptime

sites:
  - name: Google
    url: https://www.google.com
  - name: TomShani.com
    url: https://tomshani.com
status-website:
  baseUrl: /upptime # where "repo" is your repository name
  name: UppTime
